[alembic]
# Esta es la línea mágica que te está pidiendo:
script_location = app/infraestructura/alembic

# Plantilla para generar los archivos de migración
file_template = %%(year)d_%%(month)d_%%(day)d_%%(hour)d%%(minute)d-%%(rev)s_%%(slug)s

# (Opcional) URL por defecto, aunque la leeremos dinámicamente desde env.py
sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/cataclub

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S