"""esquema inicial + voucher en pago

Revision ID: c8722261ea5b
Revises: 
Create Date: 2026-07-12 17:51:00.557497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8722261ea5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo_escuela', sa.Enum('PARTICULAR', 'FISCAL', 'FISCOMISIONAL', 'MUNICIPAL', name='tipoescuela'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_rol', sa.Enum('ALUMNO', 'ENTRENADOR', 'ADMINISTRADOR', name='tiporol'), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_membresia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('franja_horaria', sa.String(length=80), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('modalidad', sa.Enum('PERSONALIZADA', 'MENSUAL', name='tipomodalidad'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provincia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canton',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barrio', sa.String(length=100), nullable=False),
    sa.Column('calle_principal', sa.String(length=150), nullable=False),
    sa.Column('calle_secundaria', sa.String(length=150), nullable=True),
    sa.Column('numero_casa', sa.String(length=20), nullable=True),
    sa.Column('canton_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['canton_id'], ['canton.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('telefono_contacto', sa.String(length=15), nullable=True),
    sa.Column('representante_id', sa.Integer(), nullable=True),
    sa.Column('direccion_id', sa.Integer(), nullable=True),
    sa.Column('institucion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['direccion_id'], ['direccion.id'], ),
    sa.ForeignKeyConstraint(['institucion_id'], ['institucion.id'], ),
    sa.ForeignKeyConstraint(['representante_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('antecedentes_club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel_tecnico_alumno', sa.Enum('NIVEL_1', 'NIVEL_2', 'NIVEL_3', 'NIVEL_4', 'NIVEL_5', 'NIVEL_6', 'NIVEL_7', 'NIVEL_8', 'NIVEL_9', 'NIVEL_10', name='niveltecnicoalumno'), nullable=False),
    sa.Column('fecha_inicio_club', sa.Date(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_table('ficha_medica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_sangre', sa.Enum('A_POSITIVO', 'A_NEGATIVO', 'B_POSITIVO', 'B_NEGATIVO', 'AB_POSITIVO', 'AB_NEGATIVO', 'O_POSITIVO', 'O_NEGATIVO', 'DESCONOCIDO', name='tiposangre'), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_table('horario_entrenamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='diasemana'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrenador_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membresia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('INACTIVA', 'ACTIVA', 'VENCIDA', name='estadomembresia'), nullable=False),
    sa.Column('monto_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_activacion', sa.DateTime(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('tipo_membresia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['tipo_membresia_id'], ['tipo_membresia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ranking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('puntaje_acumulado', sa.Integer(), nullable=False),
    sa.Column('posicion_actual', sa.Integer(), nullable=True),
    sa.Column('participo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_combate_o_asistencia', sa.DateTime(), nullable=True),
    sa.Column('esta_en_ranking', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasenia', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('persona_id')
    )
    op.create_table('asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_entrenamiento', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('PRESENTE', 'AUSENTE', 'ATRASADO', 'JUSTIFICADO', name='estadoasistencia'), nullable=False),
    sa.Column('justificativo', sa.String(length=255), nullable=True),
    sa.Column('estado_justificativo', sa.Boolean(), nullable=True),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrenador_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['horario_id'], ['horario_entrenamiento.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enfermedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_enfermedad', sa.String(length=150), nullable=False),
    sa.Column('ficha_medica_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ficha_medica_id'], ['ficha_medica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('motivo_rechazo', sa.String(length=255), nullable=True),
    sa.Column('estado_pago', sa.Enum('APROBADO', 'PENDIENTE_VALIDACION', 'RECHAZADO', name='estadopago'), nullable=False),
    sa.Column('tipo_pago', sa.Enum('EFECTIVO', 'TRANSFERENCIA', name='tipopago'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('fecha_validacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('membresia_id', sa.Integer(), nullable=False),
    sa.Column('voucher_url', sa.String(length=255), nullable=True),
    sa.Column('voucher_formato', sa.String(length=20), nullable=True),
    sa.Column('voucher_fecha_carga', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresia.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_clase_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_clase_solicitada', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADA', 'RECHAZADA', name='estadosolicitudextra'), nullable=False),
    sa.Column('costo_adicional', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('membresia_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['horario_id'], ['horario_entrenamiento.id'], ),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresia.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('comprobante_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archivo_url', sa.String(length=255), nullable=False),
    sa.Column('formato_archivo', sa.String(length=20), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pago_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comprobante_pago')
    op.drop_table('usuario_rol')
    op.drop_table('solicitud_clase_extra')
    op.drop_table('pago')
    op.drop_table('enfermedades')
    op.drop_table('asistencia')
    op.drop_table('usuario')
    op.drop_table('ranking')
    op.drop_table('membresia')
    op.drop_table('horario_entrenamiento')
    op.drop_table('ficha_medica')
    op.drop_table('antecedentes_club')
    op.drop_table('persona')
    op.drop_table('direccion')
    op.drop_table('canton')
    op.drop_table('provincia')
    op.drop_table('tipo_membresia')
    op.drop_table('rol')
    op.drop_table('pais')
    op.drop_table('institucion')
    # ### end Alembic commands ###
