"""gaps_e01_e04_roles_recuperacion_reportes

Revision ID: d3bc8c020e36
Revises: a1f3c9d02b7e
Create Date: 2026-07-15 21:45:11.845547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bc8c020e36'
down_revision: Union[str, Sequence[str], None] = 'a1f3c9d02b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DIESTRO', 'ZURDO', name='tipomanodominante').create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('antecedentes_club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mano_dominante', sa.Enum('DIESTRO', 'ZURDO', name='tipomanodominante'), nullable=True))

    with op.batch_alter_table('membresia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_gratuidad_familiar', sa.Boolean(), nullable=False))

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('prioridad_municipal', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('porcentaje_beca', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('motivo_beca', sa.String(length=150), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_contrasenia', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('version_contrasenia')

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_column('motivo_beca')
        batch_op.drop_column('porcentaje_beca')
        batch_op.drop_column('prioridad_municipal')
        batch_op.drop_column('fecha_registro')

    with op.batch_alter_table('membresia', schema=None) as batch_op:
        batch_op.drop_column('es_gratuidad_familiar')

    with op.batch_alter_table('antecedentes_club', schema=None) as batch_op:
        batch_op.drop_column('mano_dominante')
    sa.Enum(name='tipomanodominante').drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
