"""gaps_e01_e04_roles_recuperacion_tesoreria_reportes

Revision ID: d3bc8c020e36
Revises: a1f3c9d02b7e
Create Date: 2026-07-15 21:45:11.845547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bc8c020e36'
down_revision: Union[str, Sequence[str], None] = 'a1f3c9d02b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_recaudacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('meta_monto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('egreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', name='tipomovimientoevento'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento_recaudacion.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('antecedentes_club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mano_dominante', sa.Enum('DIESTRO', 'ZURDO', name='tipomanodominante'), nullable=True))

    with op.batch_alter_table('membresia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_gratuidad_familiar', sa.Boolean(), nullable=False))

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('prioridad_municipal', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('porcentaje_beca', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('motivo_beca', sa.String(length=150), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_column('motivo_beca')
        batch_op.drop_column('porcentaje_beca')
        batch_op.drop_column('prioridad_municipal')
        batch_op.drop_column('fecha_registro')

    with op.batch_alter_table('membresia', schema=None) as batch_op:
        batch_op.drop_column('es_gratuidad_familiar')

    with op.batch_alter_table('antecedentes_club', schema=None) as batch_op:
        batch_op.drop_column('mano_dominante')

    op.drop_table('movimiento_evento')
    op.drop_table('egreso')
    op.drop_table('evento_recaudacion')
    # ### end Alembic commands ###
